// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package adc_driver_csr_pkg;

    localparam ADC_DRIVER_CSR_DATA_WIDTH = 32;
    localparam ADC_DRIVER_CSR_MIN_ADDR_WIDTH = 4;
    localparam ADC_DRIVER_CSR_SIZE = 'h10;

    

    typedef struct {
        logic [31:0] next;
    } adc_driver_csr__reg_adc_counter_overflow__amount_overflow__in_t;

    typedef struct {
        adc_driver_csr__reg_adc_counter_overflow__amount_overflow__in_t amount_overflow;
    } adc_driver_csr__reg_adc_counter_overflow__in_t;

    typedef struct {
        logic [31:0] next;
    } adc_driver_csr__reg_adc_drop_word__amount__in_t;

    typedef struct {
        adc_driver_csr__reg_adc_drop_word__amount__in_t amount;
    } adc_driver_csr__reg_adc_drop_word__in_t;

    typedef struct {
        adc_driver_csr__reg_adc_counter_overflow__in_t adc_counter_overflow;
        adc_driver_csr__reg_adc_drop_word__in_t adc_drop_word;
    } adc_driver_csr__in_t;

    typedef struct {
        logic value;
    } adc_driver_csr__reg_adc_control__enable__out_t;

    typedef struct {
        adc_driver_csr__reg_adc_control__enable__out_t enable;
    } adc_driver_csr__reg_adc_control__out_t;

    typedef struct {
        logic [11:0] value;
    } adc_driver_csr__reg_adc_minampl__minampl__out_t;

    typedef struct {
        adc_driver_csr__reg_adc_minampl__minampl__out_t minampl;
    } adc_driver_csr__reg_adc_minampl__out_t;

    typedef struct {
        adc_driver_csr__reg_adc_control__out_t adc_control;
        adc_driver_csr__reg_adc_minampl__out_t adc_minampl;
    } adc_driver_csr__out_t;
endpackage
