# TCL File Generated by Component Editor 16.1
# Tue Jan 28 00:15:02 MSK 2020
# DO NOT MODIFY


# 
# ADC "ADC" v1.0
# Belenkov R.N. 2020.01.28.00:15:02
# AD9226
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ADC
# 
set_module_property DESCRIPTION AD9226
set_module_property NAME ADC
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Belenkov R.N."
set_module_property DISPLAY_NAME ADC
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL driver_ad9226
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file driver_ad9226.sv SYSTEM_VERILOG PATH driver_ad9226.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point clk_adc
# 
add_interface clk_adc clock end
set_interface_property clk_adc clockRate 0
set_interface_property clk_adc ENABLED true
set_interface_property clk_adc EXPORT_OF ""
set_interface_property clk_adc PORT_NAME_MAP ""
set_interface_property clk_adc CMSIS_SVD_VARIABLES ""
set_interface_property clk_adc SVD_ADDRESS_GROUP ""

add_interface_port clk_adc clk_adc clk Input 1


# 
# connection point clk_adc_shift
# 
add_interface clk_adc_shift clock end
set_interface_property clk_adc_shift clockRate 0
set_interface_property clk_adc_shift ENABLED true
set_interface_property clk_adc_shift EXPORT_OF ""
set_interface_property clk_adc_shift PORT_NAME_MAP ""
set_interface_property clk_adc_shift CMSIS_SVD_VARIABLES ""
set_interface_property clk_adc_shift SVD_ADDRESS_GROUP ""

add_interface_port clk_adc_shift clk_adc_shift clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avmm
# 
add_interface avmm avalon end
set_interface_property avmm addressUnits WORDS
set_interface_property avmm associatedClock clk
set_interface_property avmm associatedReset reset
set_interface_property avmm bitsPerSymbol 8
set_interface_property avmm burstOnBurstBoundariesOnly false
set_interface_property avmm burstcountUnits WORDS
set_interface_property avmm explicitAddressSpan 0
set_interface_property avmm holdTime 0
set_interface_property avmm linewrapBursts false
set_interface_property avmm maximumPendingReadTransactions 0
set_interface_property avmm maximumPendingWriteTransactions 0
set_interface_property avmm readLatency 1
set_interface_property avmm readWaitTime 1
set_interface_property avmm setupTime 0
set_interface_property avmm timingUnits Cycles
set_interface_property avmm writeWaitTime 0
set_interface_property avmm ENABLED true
set_interface_property avmm EXPORT_OF ""
set_interface_property avmm PORT_NAME_MAP ""
set_interface_property avmm CMSIS_SVD_VARIABLES ""
set_interface_property avmm SVD_ADDRESS_GROUP ""

add_interface_port avmm avmm_address address Input 2
add_interface_port avmm avmm_write write Input 1
add_interface_port avmm avmm_byteenable byteenable Input 4
add_interface_port avmm avmm_writedata writedata Input 32
add_interface_port avmm avmm_read read Input 1
add_interface_port avmm avmm_readdata readdata Output 32
add_interface_port avmm avmm_waitrequset waitrequest Output 1
set_interface_assignment avmm embeddedsw.configuration.isFlash 0
set_interface_assignment avmm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avmm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avmm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avso
# 
add_interface avso avalon_streaming start
set_interface_property avso associatedClock clk
set_interface_property avso associatedReset reset
set_interface_property avso dataBitsPerSymbol 12
set_interface_property avso errorDescriptor ""
set_interface_property avso firstSymbolInHighOrderBits true
set_interface_property avso maxChannel 0
set_interface_property avso readyLatency 0
set_interface_property avso ENABLED true
set_interface_property avso EXPORT_OF ""
set_interface_property avso PORT_NAME_MAP ""
set_interface_property avso CMSIS_SVD_VARIABLES ""
set_interface_property avso SVD_ADDRESS_GROUP ""

add_interface_port avso avso_data data Output 12
add_interface_port avso avso_ready ready Input 1
add_interface_port avso avso_valid valid Output 1


# 
# connection point otr_filter
# 
add_interface otr_filter conduit end
set_interface_property otr_filter associatedClock clk
set_interface_property otr_filter associatedReset ""
set_interface_property otr_filter ENABLED true
set_interface_property otr_filter EXPORT_OF ""
set_interface_property otr_filter PORT_NAME_MAP ""
set_interface_property otr_filter CMSIS_SVD_VARIABLES ""
set_interface_property otr_filter SVD_ADDRESS_GROUP ""

add_interface_port otr_filter otr_filter otr_filter Output 1


# 
# connection point coe_clk
# 
add_interface coe_clk conduit end
set_interface_property coe_clk associatedClock ""
set_interface_property coe_clk associatedReset reset
set_interface_property coe_clk ENABLED true
set_interface_property coe_clk EXPORT_OF ""
set_interface_property coe_clk PORT_NAME_MAP ""
set_interface_property coe_clk CMSIS_SVD_VARIABLES ""
set_interface_property coe_clk SVD_ADDRESS_GROUP ""

add_interface_port coe_clk coe_clk export Output 1


# 
# connection point coe_data
# 
add_interface coe_data conduit end
set_interface_property coe_data associatedClock ""
set_interface_property coe_data associatedReset reset
set_interface_property coe_data ENABLED true
set_interface_property coe_data EXPORT_OF ""
set_interface_property coe_data PORT_NAME_MAP ""
set_interface_property coe_data CMSIS_SVD_VARIABLES ""
set_interface_property coe_data SVD_ADDRESS_GROUP ""

add_interface_port coe_data coe_data export Input 12


# 
# connection point coe_otr
# 
add_interface coe_otr conduit end
set_interface_property coe_otr associatedClock ""
set_interface_property coe_otr associatedReset reset
set_interface_property coe_otr ENABLED true
set_interface_property coe_otr EXPORT_OF ""
set_interface_property coe_otr PORT_NAME_MAP ""
set_interface_property coe_otr CMSIS_SVD_VARIABLES ""
set_interface_property coe_otr SVD_ADDRESS_GROUP ""

add_interface_port coe_otr coe_otr export Input 1

